from time import sleep

itemUm = ("Dom Quixote. (Miguel de Cervantes)")
itemDois = ("O Conde de Monte Cristo. (Alexandre Dumas)")
itemTres = ("Um Conto de Duas Cidades. (Charles Dickens)")
itemQuatro = ("O Pequeno Príncipe. (Antoine de Saint-Exupéry)")
itemCinco = ("O Senhor dos Anéis. (J.R.R. Tolkien)")
print("Ordem dos livros que vieram de dia:")
sleep(1)
print("Primeiro Livro:{}".format(itemUm))
sleep(1)
print("Segundo Livro: {}".format(itemDois))
sleep(1)
print("Terceiro Livro: {}".format(itemTres))
sleep(1)
print("Quarto Livro: {}".format(itemQuatro))
sleep(1)
print("Quinto Livro: {}".format(itemCinco))
sleep(1)


pilha = [itemUm, itemDois, itemTres, itemQuatro, itemCinco]
print("Essa é a ordem da pilha de Livros", pilha)
sleep(1)

print("Retirada Para catalogar:")
sleep(1)
pilha.pop()
print(pilha)
sleep(1)
pilha.pop()
print(pilha)
sleep(1)
pilha.pop()
print(pilha)
sleep(1)
pilha.pop()
print(pilha)
sleep(1)
pilha.pop()
print(pilha)
sleep(1)
